"""Estado completo: Usuario, Archivo, Columna, Informe, Grafico, Filtro

Revision ID: e9cf0d1a3868
Revises: 
Create Date: 2026-09-16 00:20:40.735186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cf0d1a3868'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contraseña_hash', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('archivos_subidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=False),
    sa.Column('estado_procesamiento', sa.String(), nullable=True),
    sa.Column('mensaje_error', sa.String(), nullable=True),
    sa.Column('numero_filas', sa.Integer(), nullable=True),
    sa.Column('numero_columnas', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('hoja_seleccionada', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_subidos_id'), 'archivos_subidos', ['id'], unique=False)
    op.create_table('columnas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_columna', sa.String(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('tipo_dato', sa.String(), nullable=True),
    sa.Column('contador_valores_nulos', sa.Integer(), nullable=True),
    sa.Column('valor_minimo', sa.String(), nullable=True),
    sa.Column('valor_maximo', sa.String(), nullable=True),
    sa.Column('media', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_subidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_columnas_id'), 'columnas', ['id'], unique=False)
    op.create_table('informes_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_subidos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_informes_generados_id'), 'informes_generados', ['id'], unique=False)
    op.create_table('graficos_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('informe_id', sa.Integer(), nullable=False),
    sa.Column('columna_x_id', sa.Integer(), nullable=False),
    sa.Column('columna_y_id', sa.Integer(), nullable=True),
    sa.Column('operacion_agregacion', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipo_grafico', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('etiquetas', sa.JSON(), nullable=True),
    sa.Column('valores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['columna_x_id'], ['columnas.id'], ),
    sa.ForeignKeyConstraint(['columna_y_id'], ['columnas.id'], ),
    sa.ForeignKeyConstraint(['informe_id'], ['informes_generados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graficos_generados_id'), 'graficos_generados', ['id'], unique=False)
    op.create_table('filtros_aplicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grafico_id', sa.Integer(), nullable=False),
    sa.Column('columna_id', sa.Integer(), nullable=False),
    sa.Column('tipo_filtro', sa.String(), nullable=False),
    sa.Column('valores', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['columna_id'], ['columnas.id'], ),
    sa.ForeignKeyConstraint(['grafico_id'], ['graficos_generados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filtros_aplicados_id'), 'filtros_aplicados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filtros_aplicados_id'), table_name='filtros_aplicados')
    op.drop_table('filtros_aplicados')
    op.drop_index(op.f('ix_graficos_generados_id'), table_name='graficos_generados')
    op.drop_table('graficos_generados')
    op.drop_index(op.f('ix_informes_generados_id'), table_name='informes_generados')
    op.drop_table('informes_generados')
    op.drop_index(op.f('ix_columnas_id'), table_name='columnas')
    op.drop_table('columnas')
    op.drop_index(op.f('ix_archivos_subidos_id'), table_name='archivos_subidos')
    op.drop_table('archivos_subidos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
