"""Estado inicial: ArchivoSubido, Columna, GraficoGenerado

Revision ID: f2fcee06ac36
Revises: 
Create Date: 2026-09-13 01:02:56.857626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fcee06ac36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_subidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_archivo', sa.String(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(), nullable=False),
    sa.Column('formato', sa.String(), nullable=False),
    sa.Column('tamaño', sa.Integer(), nullable=False),
    sa.Column('estado_procesamiento', sa.String(), nullable=True),
    sa.Column('mensaje_error', sa.String(), nullable=True),
    sa.Column('numero_filas', sa.Integer(), nullable=True),
    sa.Column('numero_columnas', sa.Integer(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('hoja_seleccionada', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_subidos_id'), 'archivos_subidos', ['id'], unique=False)
    op.create_table('columnas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_columna', sa.String(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('tipo_dato', sa.String(), nullable=True),
    sa.Column('contador_valores_nulos', sa.Integer(), nullable=True),
    sa.Column('valor_minimo', sa.String(), nullable=True),
    sa.Column('valor_maximo', sa.String(), nullable=True),
    sa.Column('media', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_subidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_columnas_id'), 'columnas', ['id'], unique=False)
    op.create_table('graficos_generados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_id', sa.Integer(), nullable=False),
    sa.Column('columna_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipo_grafico', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('etiquetas', sa.JSON(), nullable=True),
    sa.Column('valores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['archivo_id'], ['archivos_subidos.id'], ),
    sa.ForeignKeyConstraint(['columna_id'], ['columnas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graficos_generados_id'), 'graficos_generados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graficos_generados_id'), table_name='graficos_generados')
    op.drop_table('graficos_generados')
    op.drop_index(op.f('ix_columnas_id'), table_name='columnas')
    op.drop_table('columnas')
    op.drop_index(op.f('ix_archivos_subidos_id'), table_name='archivos_subidos')
    op.drop_table('archivos_subidos')
    # ### end Alembic commands ###
